sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - "7.0"
  - "7.1"
  - "5.6"

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script:
  - find -L themes/royl-wp-theme-base/src -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  - phpcs --standard=phpcs.ruleset.xml $(find themes/royl-wp-theme-base/src -name '*.php')
  - phpunit
