language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
sudo: false
before_script:
  - composer install
script:
  - php vendor/bin/phpcs -p -s -v -n ./src --standard=PSR2 --extensions=php --ignore=*/src/vendor/* --ignore=src/Core/Inflector.php
  - php vendor/bin/phpunit --report-useless-tests