language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
sudo: false
before_script:
  - composer install
script:
  - find -L src -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  #- php vendor/bin/phpcs -p -s -v -n ./src --standard=PSR2 --extensions=php