language: php
php:
  - "7.0"
  - "5.6"
  - "5.5"
sudo: false
before_script:
  - composer install
script:
  - php vendor/bin/phpcs -p -s -v -n . --standard=PSR2 --extensions=php
  - php vendor/bin/phpunit --report-useless-tests