wordpress:
  image: chriszarate/wordpress
  volumes:
    - ./themes/royl-wp-theme-base:/var/www/html/wp-content/themes/royl-wp-theme-base
    - ./themes/royl-wp-theme-child:/var/www/html/wp-content/themes/royl-wp-theme-child
  links:
    - mysql:mysql
    - mysql_phpunit:mysql_phpunit
  ports:
    - 80:80
  environment:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_NAME: wordpress
    WODRPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: ""
    WORDPRESS_SITE_TITLE: "ROYL WP Theme Base Development"
    WORDPRESS_CONFIG_EXTRA: "define('WP_DEBUG', 1);"
    WORDPRESS_SITE_URL: "http://localhost"
    PHPUNIT_TEST_DIR: /var/www/html/wp-content/themes/royl-wp-theme-child
    PHPUNIT_DB_HOST: mysql_phpunit
    PHPUNIT_DB_NAME: wordpress_phpunit
    PHPUNIT_DB_USER: root
    PHPUNIT_DB_PASSWORD: ""
    XDEBUG_CONFIG: "remote_host=172.17.0.1 idekey=xdebug profiler_enable=1 profiler_output_name=%R.%t.out"

mysql:
  image: mariadb
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: ""

mysql_phpunit:
  image: mariadb
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: wordpress_phpunit
    MYSQL_ROOT_PASSWORD: ""