wordpress:
  image: chriszarate/wordpress:4.7.2
  volumes:
    - ./themes/royl-wp-theme-base:/var/www/html/wp-content/themes/royl-wp-theme-base
    - ./themes/royl-wp-theme-child:/var/www/html/wp-content/themes/royl-wp-theme-child
  links:
    - mysql:mysql
    - mysql_phpunit:mysql_phpunit
  ports:
    - 80:80
  environment:
#    WORDPRESS_ACTIVATE_PLUGINS: royl-wp-theme-base
    WORDPRESS_SITE_URL: http://localhost:8080/
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_NAME: wordpress
    WODRPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: ""
    WORDPRESS_SITE_TITLE: "ROYL WP Theme Base Development"
    WORDPRESS_CONFIG_EXTRA: "define('WP_DEBUG', 1);"
    PHPUNIT_TEST_DIR: /var/www/html/wp-content/themes/royl-wp-theme-child
    PHPUNIT_DB_HOST: mysql_phpunit
    PHPUNIT_DB_NAME: wordpress_phpunit
    PHPUNIT_DB_USER: root
    PHPUNIT_DB_PASSWORD: ""


mysql:
  image: mariadb
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: ""

mysql_phpunit:
  image: mariadb
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: wordpress_phpunit
    MYSQL_ROOT_PASSWORD: ""